name: schedule liquidation

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    branches: [master, vaults]
  pull_request:
    branches: [master, vaults]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install ts
        run: npm install -g typescript
      - name: Install ts-node
        run: npm install -g ts-node
      - name: Install Dependencies
        run: npm i
      - name: run liquidator
        run: npm run vaults
        env:
          CI: true
          PRIV_KEY: ${{ secrets.PRIV_KEY }}
          TEST: ${{ secrets.TEST }}
